### PR TITLE
Wandb updates: Separate DPO logging from IFT + add team option

### PR DESCRIPTION
**Pull request by natolambert**
Will test this shortly.

### CODE REVIEW

**Comment by hamishivi** [comment]
Did you end up testing this?

**Comment by natolambert** [comment]
@hamishivi yup, just launched a bogus job to immediately error post wandb init, but here's my new project https://wandb.ai/natolambert/open_instruct_dpo

**Comment by natolambert** [comment]
Also, with `--wandb_entity rlhf-llm-dev`
https://wandb.ai/rlhf-llm-dev/open_instruct_dpo

**Review by hamishivi — APPROVED** [review]

**Comment by hamishivi** [comment]
LGTM! Seems like your run hit some error we might need to work out at some point, but unrelated to this change.

**Comment by natolambert** [comment]
Yeah @hamishivi there was a llama 2 dpo tokenizer error that I was confused by, the assert was failing, but I commented it out to just get things running quickly to make sure this works.

Will test more soon.

**Pull request merged**
